Add support for serving on Unix domain socket
ring-clojure/ring pull request #478
Opened 2023-04-07 18:14 UTC by hsartoris-bard

## Summary
These changes take advantage of `jetty-unixsocket` to allow serving on a socket, as in the following example:

```clojure
(run-jetty handler {:http? false, :socket "/run/someapp.sock"})
```
```bash
## hostname is still required for making requests
curl --unix-socket /run/someapp.sock http://my-expected-hostname/url-path
```

## Rationale
Unix sockets are simpler to implement access controls to than TCP sockets, as you can simply use file permissions. They are supported by common reverse proxies such as Apache and NGINX, and are thus reasonable for exposing a service through a proxy that may be handling authentication, without making that service available to all users on the host machine.

## Possible enhancements:
1. Options for file ownership and access controls
2. A secure-by-default approach might see `:http?` default false when `:socket` is set, unless `:host` or `:port` are explicitly configured.
3. To avoid the additional dependency, socket support could be conditional on manually including the `jetty-unixsocket` library. It is not an overwhelmingly heavy dependency, though.

Note: it has proved nontrivial to get a test working, as clj-http does not support sockets, and the Clojure implementations that I've found do not seem to work as intended out of the box. I have verified that this implementation is operational manually, and I am willing to work through the process of getting a test working as long as you're interested in incorporating this functionality.

2023-04-09 14:19 UTC, weavejester commented
I think this is reasonable in theory. Perhaps `:unix-socket` instead of `:socket` as an option, so it's not confused with other types of sockets. Also, have you tested to ensure that the inclusion of this library doesn't cause issues when using it under operating systems that don't have sockets (e.g. Windows)? I'd also suggest not automatically deleting the socket file on startup - that feels potentially dangerous. Instead, raise an error.

2023-04-10 17:24 UTC, hsartoris-bard commented
I was under the impression that there was now unix socket support on Windows, but indeed it appears not to work. 

## Changes

- [X] check for windows
- [X] rename `:socket` to `:unix-socket`
- [X] make `:http?` default false when `:unix-socket` is set, except when `:host` or `:port` are set
- [X] throw error on extant file instead of deleting
- [X] tests for basic functionality and errant attempts to use extant file

Let me know if there's anything else you'd like to see!

2023-04-10 17:27 UTC, hsartoris-bard commented
Whoops, wasn't my intention to check in the `*warn-on-reflection*` line - I can remove that, or resolve the singular reflection warning.

2023-05-07 17:25 UTC, weavejester requested changes
Thanks for your hard work on this, and apologies for taking a while to get around to reviewing it.

2023-05-07 17:25 UTC, weavejester commented on ring-jetty-adapter/src/ring/adapter/jetty.clj
> +            #^"[Lorg.eclipse.jetty.server.ConnectionFactory;" (into-array ConnectionFactory [http-factory]))
Can you split the line over 80 characters into two lines? Also can you fix the indentation so it's according to the style guide:

```clojure
(doto (UnixSocketConnector.
       server
       ^"[Lorg.eclipse.jetty.server.ConnectionFactory;"
       (into-array ConnectionFactory [http-factory]))
```

2023-05-07 17:25 UTC, weavejester commented on ring-jetty-adapter/src/ring/adapter/jetty.clj
> +                              (some options [:host :port])))
This feels too complex, and isn't what the documentation says. I think let's keep it simple and just leave it defaulting to true. Let's add a note to the `:unix-socket` option instead to tell people they may want to set `:http?` to false.

2023-05-07 17:25 UTC, weavejester commented on ring-jetty-adapter/src/ring/adapter/jetty.clj
> +                            passed to [io/file]. Ensure there is no file at
I don't think `[io/file]` should be a link, as there's nothing to link it to.

2023-05-07 17:25 UTC, weavejester commented on ring-jetty-adapter/test/ring/adapter/test/jetty.clj
> +                    File]
These two lines should be one.

2023-05-07 17:25 UTC, weavejester commented on ring-jetty-adapter/test/ring/adapter/test/jetty.clj
> +                     (reify Supplier
Indentation looks off here.

2023-05-07 17:25 UTC, weavejester commented on ring-jetty-adapter/test/ring/adapter/test/jetty.clj
> +              clojure.lang.ExceptionInfo #"File already exists"
Indentation looks off. Please see Clojure style guide.

2023-05-07 17:25 UTC, weavejester commented on ring-jetty-adapter/src/ring/adapter/jetty.clj
> +                      {:unix-socket unix-socket})))
Let's factor this out as well:

```clojure
(defn- check-socket-file-does-not-exist [socket]
  (when (.exists socket)
    (throw (ex-info "Could not create socket file: file already exists"
                    {:socket-file (str socket)}))))
```

2024-09-26 06:34 UTC, agorgl commented
Usage of the new APIs is documented here:
https://jetty.org/docs/jetty/11/programming-guide/server/http.html#connector
https://jetty.org/docs/jetty/11/programming-guide/client/http.html#transport-unix-domain

2024-10-19 05:49 UTC, weavejester commented
Fixed by: df469736241b7ada658dc58e4b7d46e6f2003b30

2024-10-19 05:49 UTC, closed without merging