fix: websocket multi-value connection upgrades
ring-clojure/ring pull request #489
Opened 2023-11-30 23:46 UTC by rschmukler

Fixes an issue where browsers could send `keep-alive` and `Upgrade` in the same request causing the `ws/upgrade-request?` to return false.

2023-11-30 23:51 UTC, weavejester commented
Thank you for the fix! Could you change the commit description to:

```
Fix websocket multi-value connection upgrades

Fix an issue where browsers could send Keep-Alive and Upgrade in the
same request causing upgrade-request? to return false.
```

This just makes it more consistent with the other commits in Ring.

2023-11-30 23:52 UTC, rschmukler commented
@weavejester Done! Also changed the impl to handle `nil` values. Sorry for the noise. Didn't run the tests locally before submitting the PR. Works now!

2023-12-06 04:47 UTC, weavejester requested changes
So I reviewed this a few days ago, but I forgot to submit the review, and only just noticed that my comment had "Pending" attached to it. So many apologies for the late response.

2023-12-06 04:50 UTC, rschmukler commented
No problem at all! Yours looks good! I can submit an amended commit tomorrow (about 12 hours) or you're welcome to commit whatever you feel is best. 

Cheers!

2023-12-07 01:36 UTC, weavejester approved these changes

2023-12-07 01:37 UTC, merged